# yaml definition of job which execute a workload until ifit's finished
# A job run behind the scene a job which status i completed once the job is completed
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: pi
  labels:
    app: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command:
        - 'perl'
        - '-Mbignum=bpi'
        - '-wle'
        - 'print bpi(2000)'
      restartPolicy: Never
  backoffLimit: 4   

