apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-cleanup
spec:
  schedule: "*/1 * * * *"  # cron job to execute load every minute
  jobTemplate:
    spec:
      template:
        metadata:
          labels: 
            app: data-cleanup
        spec:
          containers:
          - name: data-cleanup
            image: linuxacademycontent/data-cleanup:1
          restartPolicy: OnFailure

