apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels: 
    app: counter
spec:
  containers:
  - name: count
    image: busybox
    command:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date)" >> /var/log/1.log;
        echo "$(date) INFO $i" >> /var/log/2.log;
        i=$((i+1));
        sleep 1;
      done 
    volumeMounts:
    - mountPath: "/var/log"
      name: "adapter-volume"   
  - name: adapter
    image: k8s.gcr.io/fluentd-gcp:1.30
    env:
    - name: FLUENTD_ARGS 
      value: "-c /fluentd/etc/fluent.conf"
    volumeMounts:
    - mountPath: "/fluentd/etc"
      name: "configmap-volume"
    - mountPath: "/var/log"
      name: "adapter-volume"
    - mountPath:  /var/logout
      name: "hostpath-volume"   
  volumes:
  # ConfigMap volume that contains configuration data
  - name: configmap-volume
    configMap: 
      name: fluentd-config
  # Internal storage volume that is lost when the pod dies
  - name: adapter-volume
    emptyDir: {}
  # A hostPath volume allow hosting a file or dir from host node filesystem into our Pod
  - name: hostpath-volume
    hostPath:
      path: /usr/ckad/log_output



