# To test service localhost:nodePort
apiVersion: v1
kind: Service
metadata: 
  name: pizza-service
spec:
  selector:
    app: pizza-service
  ports:
  - protocol: TCP
    nodePort: 30080 
    port: 80
  type: NodePort  

