apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  # define the type of service
  type: NodePort
  selector: 
    app: auth
  ports:
  # define the protocol uses by the service to forward traffic
  - protocol: TCP
    # define the port on which the service listen on  
    port: 8080
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: data-svc
spec:
  # define the type of service
  type: ClusterIP
  selector: 
    app: data
  ports:
  # define the protocol uses by the service to forward traffic
  - protocol: TCP
    # define the port on which the service listen on  
    port: 8080
    targetPort: 80     