apiVersion: v1
kind: Pod
metadata:
  name: my-liveness-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo Hello, Kubernetes! && sleep 3600"]
    livenessProbe:
      exec: # allow to run a command to determine the result of the probe
        command: # the if the console inside the probe is responsive, if not responsive the container fail is then restart
        - echo
        - testing
      initialDelaySeconds: 5 # wait 5 seconds before running the probe
      periodSeconds: 5 # run every  seconds