apiVersion: v1
kind: Pod
metadata:
  name: my-readiness-pod
spec:
  containers:
  - name: myapp-container
    image: nginx
    readinessProbe:
      # an http request probe, the readiness probe will perform an http get request to the pod,
      # an the response will determine if the pod is ready to service request
      httpGet: 
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5