apiVersion: v1
kind: Pod
metadata:
  name: candy-service-pod
spec:
  serviceAccountName: candy-svc 
  # Gestion de la sécurité dans un Pod, droit d'accès des utilisateurs
  securityContext: 
    #runAsUser: 1000
    fsGroup: 2000
  containers:
    - name: candy-service-pod
      image: linuxacademycontent/candy-service:1
      volumeMounts:
      - name: candy-service-volume
        mountPath: /etc/candy-service
      # command: ['sh', '-c', "echo $(MY_PASSWORD) && sleep 3600"]
      # Resource requirement of a Pod, set the amount of memomry and cpu. We define the resource request and limit
      resources:
        requests:
          memory: "65Mi" 
          cpu: "250m"
        limits:
          memory: "65Mi"
          cpu: "250m"
      env:
      - name: MY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-password
            key: password
  volumes:
    - name: candy-service-volume
      configMap:
        name: candy-service-config