apiVersion: v1
kind: Pod
metadata:
  name: fruit-service
spec:
  containers:
  - name: fruit-service
    image: linuxacademycontent/legacy-fruit-service:1
  - name: fruit-service-ambassador
    image: haproxy:1.7
    ports:
    - containerPort: 80
    volumeMounts:
    - name: fruit-service-volume
      mountPath: /usr/local/etc/haproxy
  volumes:
  - name: fruit-service-volume
    configMap:
      name: fruit-service-ambassador-config

